# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bf4934ab790aef66072dab44f320ab8c78f0557f41213c9c096dd1ef995b2a0932ef874c0cb2dcf4778120be7dcdd9adb2d095196b025b033208d17dfa5dcac

test:
  secret_key_base: d8a395f8a3583d2a93e1f4ed4e55d2aa95ca929c3cc894f3db9ba17428459fb87b23fe22c1a3c35e6bf2677bbc3383530bda697815a47dae8ea95eb6ff6865b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
